
version: "3"

services:
  backend_db:
    image: postgres:10.7
    ports:
      - "15432:5432"
    environment:
        - POSTGRES_DB=backend
        - POSTGRES_USER=backend
        - POSTGRES_PASSWORD
        - POSTGRES_ROOT_PASSWORD
    volumes:
      - backend_postgresql:/var/lib/postgresql
      - backend_postgresql_data:/var/lib/postgresql/data
  backend:
      build: .
      command: ["go", "run", "cmd/backend/main.go"]
      environment:
        - LOGLEVEL=DEBUG
        - PGDATASOURCE=postgres://backend:${POSTGRES_PASSWORD}@postgres/backend?sslmode=disable
        - ADDR=:8080
        - STAGE=local
        - BRANCH=master
      depends_on:
        - backend_db
      links:
        - backend_db:postgres
      ports:
        - "18443:8443"
        - "18080:8080"
      volumes:
        - backend_gomod_data:/go/pkg/mod
        - .:/src
volumes:
  backend_postgresql:
  backend_postgresql_data:
  backend_gomod_data:
